name: Lint Packer Templates

on:
  push:
    branches: [main]
    paths:
      - 'packer/**'
  pull_request:
    paths:
      - 'packer/**'

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Packer
        uses: hashicorp/setup-packer@ce93c3c08a6c2ff2275bf4b54ff0d9a75f6c9789 # v3.4.0
        with:
          version: latest

      - name: Initialize Packer
        run: |
          cd packer
          packer init .

      - name: Format and validate Packer template
        run: |
          cd packer
          packer fmt -check .
          packer validate .
